# Generated by Django 3.2.4 on 2026-04-15 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('element', models.CharField(choices=[('fire', 'Fire'), ('earth', 'Earth'), ('air', 'Air'), ('water', 'Water')], max_length=10)),
                ('ruling_planet', models.CharField(max_length=30)),
                ('date_range', models.CharField(help_text="e.g. 'March 21 – April 19'", max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('love', models.TextField()),
                ('career', models.TextField()),
                ('health', models.TextField()),
                ('overall', models.TextField()),
                ('lucky_number', models.PositiveSmallIntegerField()),
                ('lucky_color', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='human_ast_app.zodiacsign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('zodiac_sign', 'date')},
            },
        ),
    ]
