# Generated by Django 3.2.4 on 2026-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='always_available',
            field=models.BooleanField(default=False, help_text='If checked, this item appears on breakfast, lunch, and dinner menus.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10, null=True),
        ),
    ]
